name: "Plantilla gen茅rica de Issue"
description: "Template con campos de T铆tulo, Descripci贸n, Requisitos, Criterios de Aceptaci贸n y Labels"
title: "[Issue] "
labels: []
assignees: []
body:
  - type: markdown

    attributes:
      value: |
         **Por favor completa los siguientes campos para describir tu Issue.**

  - type: textarea

    id: descripcion
    attributes:
      label: "Descripci贸n"
      description: "Explica lo que se busca lograr"
      placeholder: |
        Crear el sistema de pr茅stamos que utilice hilos y el patr贸n productor-consumidor para procesar solicitudes de pr茅stamo en tiempo real.
    validations:
      required: true

  - type: textarea

    id: requisitos
    attributes:
      label: "Requisitos"
      description: "Lista las tareas o requisitos clave"
      placeholder: |
        - Implementar BlockingQueue para solicitudes de pr茅stamo
        - Crear procesador de solicitudes usando ExecutorService
        - Implementar sistema de notificaciones
        - Asegurar thread-safety en operaciones de pr茅stamo
    validations:
      required: true

  - type: textarea

    id: criterios_aceptacion
    attributes:
      label: "Criterios de Aceptaci贸n"
      description: "Define c贸mo saber que el Issue est谩 completo"
      placeholder: |
        - Sistema procesa pr茅stamos concurrentemente
        - Manejo adecuado de excepciones
        - Documentaci贸n de dise帽o
    validations:
      required: true


